# permissions for end users to view databaseengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: databaseengine-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dbaas-operator
    app.kubernetes.io/part-of: dbaas-operator
    app.kubernetes.io/managed-by: kustomize
  name: databaseengine-viewer-role
rules:
- apiGroups:
  - dbaas.percona.com
  resources:
  - databaseengines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.percona.com
  resources:
  - databaseengines/status
  verbs:
  - get
