# permissions for end users to edit databaseclusterbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databaseclusterbackup-editor-role
rules:
- apiGroups:
  - dbaas.percona.com
  resources:
  - databaseclusterbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.percona.com
  resources:
  - databaseclusterbackups/status
  verbs:
  - get
