apiVersion: dbaas.percona.com/v1
kind: DatabaseCluster
metadata:
  name: single-node4
  namespace: default
spec:
  databaseType: psmdb
  databaseImage: percona/percona-server-mongodb:5.0.14-12
  databaseConfig: ""
  secretsName: pxc-sample-secrets
  clusterSize: 1
  loadBalancer:
    type: mongos
    exposeType: ClusterIP
    size: 1
  dbInstance:
    cpu: "1"
    memory: 1G
    diskSize: 15G


