apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: true
kindConfig: e2e-tests/kind.yml
crdDir: config/crd/bases
artifactsDir: /tmp/
testDirs:
- e2e-tests/tests
commands:
  - command: kubectl apply -f https://raw.githubusercontent.com/percona/percona-xtradb-cluster-operator/v${PXC_OPERATOR_VERSION}/deploy/bundle.yaml -n "${NAMESPACE}"
  - command: ./bin/manager
    background: true
