apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: true
kindConfig: e2e-tests/kind.yml
crdDir: config/crd/bases
artifactsDir: /tmp/
testDirs:
- e2e-tests/tests
commands:
  - command: ./bin/manager
    background: true
